@extends('layouts.app')

@section('title', 'Competitividad')

@section('content')
<div class="container">
    <h1>Competitividad</h1>
    <p>Contenido de la página de Competitividad.</p>

    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a quam non nunc egestas varius sit amet placerat neque. Morbi accumsan diam vitae euismod euismod. Ut ut quam consequat, varius erat sollicitudin, sagittis erat. Mauris at ultrices magna. Fusce in venenatis augue. Fusce dolor neque, interdum quis risus sed, scelerisque pretium metus. Duis in aliquam nunc. Proin tincidunt massa id tellus porta, vel rhoncus ante auctor. Praesent ullamcorper augue et vulputate volutpat. Proin eu lectus mattis, sagittis lorem sed, ullamcorper erat. Proin accumsan imperdiet eros. Quisque semper iaculis mi, eu euismod sapien varius ac. Morbi et hendrerit mi. Sed aliquet dictum rutrum.

        Pellentesque a augue ac turpis finibus euismod eget quis dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent non quam ac erat maximus lacinia eu eu enim. Vivamus semper, metus nec porta posuere, lacus erat pretium est, a porta libero dolor a risus. In ut urna in eros condimentum posuere ut at est. Cras ut porta elit. Vivamus vestibulum porttitor elit at auctor. Proin at sem id nibh volutpat finibus eget pharetra dui. Mauris tortor ipsum, aliquet id nisl et, pellentesque placerat ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in venenatis ligula. Fusce est ante, sollicitudin quis mollis sed, aliquam sed ligula. Sed non fringilla turpis. Vestibulum rhoncus diam leo, ac varius lacus porttitor ut. Nam ut lorem nunc. Aenean vel arcu vel tellus sagittis suscipit.
        
        Etiam purus est, dapibus vitae euismod vel, accumsan sit amet lectus. Morbi porta tortor ante. Aliquam lacinia tincidunt massa at iaculis. Morbi tristique mi felis, ac commodo odio elementum sed. Donec vulputate risus eget mauris finibus, sed accumsan lorem eleifend. Nam pretium enim at turpis consectetur euismod. Praesent sapien lectus, lobortis sit amet elementum id, vulputate quis odio.
        
        Nullam egestas ultrices nulla id ullamcorper. Praesent semper dictum enim, eu sodales dui dictum in. Nunc laoreet maximus elit malesuada volutpat. Duis sodales dictum dignissim. Aenean elementum nibh aliquet, volutpat leo non, bibendum est. Quisque eget massa euismod nisl pharetra pretium. Pellentesque turpis turpis, euismod nec mi at, fermentum laoreet dui. Curabitur a lacinia leo. Vivamus faucibus, eros ut rutrum interdum, mauris tortor condimentum odio, vel porttitor enim massa vitae elit. Duis et enim dignissim, posuere felis in, ultricies odio. Integer condimentum mi turpis, placerat eleifend eros aliquam vitae.
        
        Pellentesque vitae eleifend nisl. Quisque tincidunt dolor arcu, et eleifend ipsum hendrerit tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc orci arcu, eleifend non posuere a, congue nec nisl. Vivamus et purus sit amet odio bibendum ultricies. Integer bibendum ligula nisi, viverra fringilla neque facilisis ut. Pellentesque rhoncus purus ipsum, quis viverra urna pellentesque vitae. Nulla vestibulum, tellus a cursus dictum, erat nulla auctor metus, vitae tincidunt lacus enim congue nunc. Mauris non gravida odio, vel placerat massa. Praesent fermentum convallis cursus. Praesent in interdum nisl. Cras faucibus ipsum vel eros aliquet, a scelerisque odio sagittis. Integer ut gravida odio, a tempus ipsum. Pellentesque consequat mauris quis nulla efficitur, eu euismod libero rutrum. Quisque velit metus, efficitur ut ipsum non, lobortis sollicitudin tortor. Pellentesque ex arcu, blandit id sodales vitae, varius a lorem.
        
        Cras ut suscipit massa. Proin vel purus ac ex dapibus consequat at at orci. Duis purus odio, dapibus nec maximus in, dictum et est. Sed bibendum tellus dui, nec viverra lectus elementum eu. Aliquam odio dolor, pulvinar eget varius vitae, dictum eu est. Fusce elementum lectus nibh, quis aliquam sapien vestibulum sit amet. Cras consectetur eu erat id sagittis. Nullam in lectus vel quam luctus lacinia. Donec sed diam at dolor molestie pretium at sit amet purus. Cras porttitor fringilla feugiat. Fusce tincidunt sodales dui sed vehicula.
        
        Suspendisse feugiat consectetur velit ut lobortis. Nullam et cursus orci. Vestibulum in malesuada urna. Morbi ultricies fringilla pharetra. In et odio non tellus rhoncus varius. Donec at sem non mi posuere placerat a ac est. Fusce eu odio ac arcu bibendum mattis et et eros. Fusce eros magna, varius sed est a, volutpat venenatis purus. Praesent gravida hendrerit varius. Quisque maximus leo non nisl tincidunt, tempus venenatis tortor pharetra. Donec molestie mauris tempus consequat hendrerit. Phasellus quis pellentesque risus, id congue libero. Suspendisse lobortis nec lorem vel fringilla. Duis vehicula nulla in efficitur viverra. Vestibulum sit amet velit accumsan, efficitur nisi ac, sagittis erat.
        
        Integer ac leo auctor, sagittis velit nec, consequat neque. Donec malesuada erat nec quam pulvinar viverra. Nunc ornare pulvinar ipsum. Nullam cursus lacinia sagittis. Proin dolor urna, facilisis quis aliquet in, dignissim vitae metus. Nullam dapibus lorem vel massa sagittis, nec interdum elit tincidunt. Nam congue tristique dapibus. Donec mollis tincidunt dolor, id feugiat diam pretium eget.
        
        Proin commodo consequat pharetra. Nunc rhoncus maximus consectetur. Nunc condimentum libero et elit consectetur hendrerit. Curabitur quis rutrum justo, eu vehicula sapien. Duis elementum quis eros vel scelerisque. Duis leo ex, interdum quis varius sed, iaculis a odio. Integer et risus interdum, efficitur eros ac, mattis turpis. Ut bibendum neque non ante malesuada placerat.
        
        Ut feugiat mollis eros, eu euismod erat sodales ac. Quisque nec massa tincidunt, tristique nisl eget, consequat enim. Proin lacinia neque vel libero efficitur, a finibus enim placerat. Vestibulum vel neque ante. Aliquam elementum odio posuere tincidunt efficitur. Nam vestibulum nisi non diam placerat, id vestibulum nulla interdum. Praesent mauris tortor, sodales in libero nec, pellentesque rutrum nibh. Curabitur ut venenatis eros.
        
        Mauris pretium lacus at augue ultricies aliquet. Curabitur facilisis ac dui a euismod. Vestibulum eget elit ornare, sollicitudin sem sed, consequat ligula. Maecenas neque lorem, convallis in sollicitudin vel, bibendum ut ipsum. Nulla feugiat vulputate sem, sit amet cursus sapien maximus non. Integer et tristique nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam tempor commodo orci eu consequat. Mauris nec accumsan erat.
        
        Praesent vestibulum luctus commodo. Quisque sit amet metus et tortor posuere vehicula eget ac elit. Proin aliquet laoreet justo eu finibus. Praesent ligula ligula, cursus ac ullamcorper sit amet, placerat a nibh. Aliquam erat volutpat. Aenean eget lectus felis. Integer porttitor leo ac sem mattis, non commodo risus congue. Aliquam pharetra cursus egestas. In sagittis quam in felis vehicula eleifend. In facilisis eget sem ac imperdiet. Vestibulum posuere lectus vel commodo pharetra. Integer hendrerit diam nec sapien varius facilisis.
        
        Aenean id sollicitudin nulla. Praesent quis lacus laoreet, aliquam magna a, condimentum quam. Vestibulum efficitur ultricies pretium. Praesent mattis, est ac sollicitudin consequat, erat nulla interdum est, scelerisque accumsan massa nunc sed lectus. Morbi sit amet elit risus. Mauris sit amet quam sem. Sed ultrices vehicula dolor. Maecenas tempor metus at dolor egestas, eget aliquet justo facilisis. Nam a mauris aliquam, egestas libero vitae, facilisis purus. Fusce id vulputate ante. Suspendisse ullamcorper nunc eu mi vulputate, sit amet rhoncus ante pretium. Quisque dui dui, lacinia quis ultrices quis, auctor vel neque. Aenean in auctor nisi. Pellentesque euismod lectus vel augue interdum, ut blandit sapien scelerisque. Integer sit amet lectus vel nisi congue aliquam. Pellentesque gravida interdum augue, vel ultricies tellus vulputate nec.
        
        Etiam imperdiet porttitor nibh et tempus. Etiam eget ex at neque finibus dapibus. Sed egestas ultricies ligula et eleifend. Mauris efficitur nulla mi, et eleifend nunc tristique sed. Integer ac egestas purus. Nullam sed urna libero. Ut dignissim sapien non libero ullamcorper dignissim. Maecenas euismod augue quis ligula dictum mollis. Proin nec orci sed lectus gravida scelerisque nec eu est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In aliquet neque in ipsum fermentum, euismod dapibus lacus suscipit.
        
        Etiam auctor, neque et malesuada laoreet, odio magna ultricies erat, vel accumsan mi ex nec magna. Donec blandit tempor vulputate. Nunc consequat nec eros quis semper. Suspendisse potenti. Quisque massa felis, ullamcorper a laoreet eu, faucibus in ligula. Curabitur consequat varius ligula, vel molestie tellus tincidunt in. Suspendisse ac ipsum id sapien dignissim varius. Aliquam ante ipsum, venenatis a condimentum eu, tincidunt ac libero. Aliquam vitae molestie neque. Suspendisse vitae tortor tortor. Nam eget erat nec ex placerat imperdiet at vitae dui.</div>
</div>
@endsection